apiVersion: apps/v1
kind: Deployment
metadata:
  name: hout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hout
  template:
    metadata:
      labels:
        app: hout
    spec:
      containers:
      - image: okteto.dev/hout:latest
        name: hout
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "b09bd908-870a-46ee-9e79-3e6644088aa6"
        - name: Vless_Path
          value: "/TYAWR"
        - name: Vmess_UUID
          value: "b09bd908-870a-46ee-9e79-3e6644088aa6"
        - name: Vmess_Path
          value: "/LUHGTYR"
        - name: Share_Path
          value: "/share233"
